spring.datasource.url=jdbc:postgresql://ep-morning-forest-aoa3apow.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Z4QNcJiRKu6d&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=M@N%6264

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect